name: ci
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #переносит репозиторий в выбранную выше среду
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install
      - name: Run linter
        run: make lint
      - name: Test
        run: make pytest
      # - name: Test & publish code coverage
      #   uses: paambaati/codeclimate-action@v3.0.0
      #   env:
      #     CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
      #   with:
      #     coverageCommand: make pytest
      #     debug: true
